### ISSUE TITLE
Make todo list in dashboard page

### ISSUE THREAD

**Issue by sob-alex** [sob-alex/react-forms-multistep#1]
Tasks:
- [x] Add two text field for entering todos
- [x] Add todo card with oportunity of deleting, editing, complete marking
- [x] Add searching by title
- [x] Set up redux for todo lists
